nama = input('Nama: ')
nim = input('NIM: ')
kelas_paralel = input('Kelas Paralel: ')
Ttl = input('Tempat/Tanggal Lahir: ')
Alamat = input('Alamat: ')
Hobby = input('Hobby: ')
Hp = input('No.HP: ')
 
print("Output")
   
print('Nama: ',nama)
print('NIM: ',nim)
print('Kelas Paralel: ',kelas_paralel)
print('Tempat/Tanggal Lahir: ',Ttl)
print('Alamat: ',Alamat)
print('Hobby: ',Hobby)
print('Hp: ', Hp)